/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    AppNotification: typeof import('./src/components/AppNotification.vue')['default']
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ExploreItem: typeof import('./src/components/ExploreItem.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetFriendSuggestions: typeof import('./src/components/WidgetFriendSuggestions.vue')['default']
    WidgetRelatedContent: typeof import('./src/components/WidgetRelatedContent.vue')['default']
  }
}
